### ISSUE TITLE
Not enough memory available for this task. Playsound module error

### ISSUE THREAD

**Issue by Zx-EvM** [portasynthinca3/ppfun2#1]
Python 3.8
Windows 10 19041.508 2004

![Screenshot (76)](https://user-images.githubusercontent.com/20873402/94247440-7601e380-ff60-11ea-927b-a041a03dba78.png)

**Comment by Zx-EvM** [comment]
I was have 10 Gb RAM available

**Comment by Zx-EvM** [comment]
@portasynthinca3 looks like the `playsound` module not supported by the developer and has many bugs (many opens issues from 2019). Last commit was 5 years ago.

Maybe use https://github.com/pygame/ or https://github.com/jiaaro/pydub for this purposes?

**Comment by Zx-EvM** [comment]
Update: also I note that error causes every time after several activations of the playsound function

**Comment by Zx-EvM** [comment]
😂 I just find out what exactly cause error. If we want to save `playsound` dependency we need to patch it ourselves.

We just should close each created LAV instance after the sound finish playing. So we need to change:

https://github.com/TaylorSMarks/playsound/blob/907f1fe73375a2156f7e0900c4b42c0a60fa1d00/playsound.py#L40-L41

```py
    if block:
        sleep(float(durationInMS) / 1000.0)
```
to:

```py
    if block:
        sleep(float(durationInMS) / 1000.0)
        winCommand('close', alias)
```

**Comment by portasynthinca3** [comment]
Wow! I should issue a PR to the library creator and this issue should be resolved. Thanks for spotting the leak!

**Comment by portasynthinca3** [comment]
Nope, not happening. There is a PR for this since august 14th. Let's see if I can find another library.

**Comment by portasynthinca3** [comment]
Moved from `playsound` to `pydub` in version `1.1.8`. The issue should be resolved now.
